steps:
  # Upload Master Code
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "-r", "master", "gs://collaborative-teaching.appspot.com/"]

  # Upload Load Balancer Code
  - name: "gcr.io/cloud-builders/gsutil"
    args:
      ["cp", "-r", "load_balancer", "gs://collaborative-teaching.appspot.com/"]

  # Upload Database Startup Script
  - name: "gcr.io/cloud-builders/gsutil"
    args:
      [
        "cp",
        "-r",
        "scripts",
        "gs://collaborative-teaching.appspot.com/",
      ]

  # Install Master dependencies
  - name: "gcr.io/cloud-builders/npm"
    dir: "master"
    args: ["ci"]

  # Build Master 1
  - name: "gcr.io/cloud-builders/npm"
    dir: "master"
    args: ["run", "build"]
    env:
      - "SERVICE_NAME=master1"

  # Deploy Master 1
  - name: "gcr.io/cloud-builders/gcloud"
    dir: "master/build"
    args: ["app", "deploy"]

  # Install React app dependencies
  - name: "gcr.io/cloud-builders/npm"
    dir: "client"
    args: ["ci"]

  # Build React app
  - name: "gcr.io/cloud-builders/npm"
    dir: "client"
    args: ["run", "build"]

  # Deploy React app
  - name: "gcr.io/$PROJECT_ID/firebase"
    dir: "client/build"
    args:
      [
        "deploy",
        "--debug",
        "--token",
        "1//06Wz6HOOUk265CgYIARAAGAYSNwF-L9IrZCyVKSN4_P45z2IQub1idM4TUTRR_hUnjD2u4KelPHAU83ikSIqj2E63fwHX5UeaOt4",
      ]
timeout: "1000s"
